//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_14.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p=4,72 v=24,-91
        ///p=54,28 v=82,-76
        ///p=2,89 v=-9,57
        ///p=17,70 v=-32,-17
        ///p=81,98 v=-74,-59
        ///p=58,73 v=-2,20
        ///p=75,13 v=-77,94
        ///p=31,24 v=-27,-28
        ///p=16,64 v=68,3
        ///p=74,25 v=-62,4
        ///p=67,62 v=-78,-70
        ///p=47,101 v=-65,-79
        ///p=53,29 v=-86,39
        ///p=57,39 v=13,-53
        ///p=75,64 v=55,-98
        ///p=24,87 v=94,11
        ///p=47,32 v=-28,85
        ///p=64,24 v=-9,87
        ///p=52,39 v=-49,-17
        ///p=7,6 v=55,1
        ///p=73,67 v=10,-48
        ///p=13,35 v=-33,-61
        ///p=75,66 v=-74,-4
        ///p=37,45 v=-30,69
        ///p=70,85 v=85,-72
        ///p=69,41 v=12,39
        ///p=89,30 v=40,2
        ///p=27,22 v=10,3
        ///p=37,9 v=59,14
        ///p=62,6 v=-76,-24
        ///p=77,80 v=-87, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
