//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_5.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11|42
        ///53|45
        ///53|81
        ///21|97
        ///21|88
        ///21|22
        ///29|27
        ///29|78
        ///29|81
        ///29|66
        ///64|63
        ///64|52
        ///64|92
        ///64|82
        ///64|72
        ///56|36
        ///56|29
        ///56|78
        ///56|73
        ///56|55
        ///56|84
        ///59|18
        ///59|14
        ///59|13
        ///59|19
        ///59|88
        ///59|75
        ///59|16
        ///42|41
        ///42|16
        ///42|53
        ///42|56
        ///42|52
        ///42|59
        ///42|88
        ///42|29
        ///13|43
        ///13|79
        ///13|11
        ///13|97
        ///13|27
        ///13|45
        ///13|42
        ///13|66
        ///13|21
        ///16|18
        ///16|78
        ///16|41
        ///16|75
        ///16|13
        ///16|68
        ///16|54
        ///16|82
        ///16|84
        ///16|88
        ///79|36
        ///79|52
        ///79|82
        ///79|63
        ///79|53
        ///79|75
        ///79|72
        ///79|91
        ///79|78
        ///79|18
        ///79|73
        ///68|69
        ///68|76
        ///68|32
        ///68|45
        ///68|27
        ///68|42
        ///68|66
        ///68|21
        ///68|71
        ///68|11
        ///68|54
        ///68|95
        ///72|92
        ///72|66
        ///72|65
        ///72|13
        ///72|68
        ///72|71
        ///72|76
        ///72 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
    }
}
